### PR TITLE
wrap RPC calls in mutex

### PR DESCRIPTION
**Pull request by chetan**
This is an update to #29 
* Calls into the EVM need to be serialized as it is not thread-safe

### CODE REVIEW

**Comment by chetan** [comment]
@tcoulter can you test this and see if you still hit the same bug?

**Comment by tcoulter** [comment]
@chetan On it.

**Comment by tcoulter** [comment]
@chetan My app seems to reproduce the nonce bug 100% without this fix. And with this fix it seems to be 100% back to normal. Gonna merge and use this for a day or so to see if anything else pops up. Then will deploy a new version. Thanks a lot for your work!

**Comment by tcoulter** [comment]
@chetan FYI: I’m getting this now - just started happening, and it seems running my tests somehow expose the error (though I'm still drilling down to see if there's an obvious culprit). Any ideas? 
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
TRACE:eth.vm.exit	EXIT cause=STOP
127.0.0.1 - - [27/Oct/2015 13:51:49] "POST / HTTP/1.1" 200 -
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/site-packages/jsonrpclib/SimpleJSONRPCServer.py", line 185, in do_POST
    self.connection.shutdown(1)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 57] Socket is not connected
————————————————————
```

**Comment by chetan** [comment]
Strange. It sounds like it's trying to close a handle where the client has already disconnected. Don't think this is related to this change, but not sure..

**Comment by chetan** [comment]
Ok never mind, I see what's going on now. Sounds like the problem is simply a matter of SimpleJSONRPCServer not properly catching this error. I think the fix needs to happen there. 
FWIW, when I looked into the issue originally, I looked at other rpc libs for one that uses a more robust HTTP implementation. I think there are a couple options but they would require more changes to the setup code.  





On Tue, Oct 27, 2015 at 2:02 PM -0700, "Tim Coulter" <notifications@github.com> wrote:












@chetan FYI: I’m getting this now - just started happening, and it seems running my tests somehow expose the error (though I'm still drilling down to see if there's an obvious culprit). Any ideas? 

Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
TRACE:eth.vm.exit   EXIT cause=STOP
127.0.0.1 - - [27/Oct/2015 13:51:49] "POST / HTTP/1.1" 200 -
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/site-packages/jsonrpclib/SimpleJSONRPCServer.py", line 185, in do_POST
    self.connection.shutdown(1)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 57] Socket is not connected
————————————————————

**Comment by tcoulter** [comment]
If you could use one of the more robust ones, that'd be great. Unfortunately python isn't my strong suit and I've been maintaining the project by the seat of my pants. Assuming it's not too much work, could you give it a shot?

**Comment by chetan** [comment]
Sure, I'll take a look

**Comment by tcoulter** [comment]
Hey @chetan, have you been able to take a look at this? The frequency of this bug is great enough that it's hard to get through a single runthrough of our apps test suite. I'll have to revert your recent changes to keep things stable, but would much rather love a fix for the issue. Let me know if you have any ideas.

**Comment by tcoulter** [comment]
That is, unless you think it has nothing to do with your changes. I'll try an older version and see what happens.

**Comment by chetan** [comment]
Haven't had a chance yet and might not get to it til Monday. Will keep you posted. 






On Thu, Oct 29, 2015 at 3:19 PM -0700, "Tim Coulter" <notifications@github.com> wrote:












That is, unless you think it has nothing to do with your changes. I'll try an older version and see what happens.

**Pull request merged**
