### PR TITLE
Make the rpc server usable outside of the command line

### PR DESCRIPTION
**Pull request by pipermerriam**
### What is the problem?

I need to use the `server` object from `testrpc.__main__` from within python codebase.  The current code instantiates the server using command line arguments for `host` and `port` which don't allow the flexibility that I need (ability to run on a different or dynamic port)

### How was this fixed.

I created a new function `create_server` in the `testrpc.__main__` module that handles the server creation.  This allows me to import this function so that I can generate new instances of the server.

#### Cute animal picture

animals-in-pajamas-7

### CODE REVIEW

**Comment by tcoulter** [comment]
Looks good. I'm in bed now but should merge tomorrow (Thursday) morning.

**Comment by pipermerriam** [comment]
Awesome and thanks.

**Comment by tcoulter** [comment]
Merging. You need a new pipy release to go along with it?

**Comment by pipermerriam** [comment]
Ideally yes on the `pypi` release.  Appreciate you working with me on this.

**Comment by tcoulter** [comment]
Done.

**Pull request merged**
